version: '3'

tasks:
  default: 
    desc: Просмотр всех команд
    cmds:
      - task --list-all

  frontend:
    desc: Запуск frontend
    cmds:
      - cd frontend && npm start

  backend:
    desc: Запуск backend 
    cmds:
      - cd backend && yarn dev

  db:
    desc: Запуск базы данных
    cmds:
      - cd .infra && docker compose up -d
