version: '3.8'

services:
  db:
    image: mysql
    # command: --default-authentication-plugin=mysql_native_password
    container_name: ${PROJECT}_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:3306"

  # backend:
  #   image: node
  #   container_name: ${PROJECT}_backend
  #   restart: unless-stopped
  #   ports:
  #     - "${BACKEND_PORT}:3000"